"""
Report generation service - HTML and PDF reports
"""

import os
from datetime import datetime
from flask import current_app

def generate_html_report(upload_id, metrics, df_preview=None):
    """
    Generate HTML quality report.
    
    Args:
        upload_id (int): Upload ID
        metrics (dict): Quality metrics data
        df_preview (DataFrame, optional): Preview of data
    
    Returns:
        str: HTML content as string
    """
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Build HTML report
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Data Quality Report - Upload {upload_id}</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                background-color: #f5f5f5;
            }}
            .container {{
                max-width: 1200px;
                margin: 0 auto;
                background-color: white;
                padding: 30px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }}
            h1 {{
                color: #2c3e50;
                border-bottom: 2px solid #3498db;
                padding-bottom: 10px;
            }}
            .summary {{
                display: flex;
                gap: 20px;
                margin: 20px 0;
            }}
            .card {{
                background: #ecf0f1;
                padding: 15px;
                border-radius: 8px;
                flex: 1;
                text-align: center;
            }}
            .card h3 {{
                margin: 0 0 10px 0;
                color: #2c3e50;
            }}
            .card .number {{
                font-size: 28px;
                font-weight: bold;
                color: #3498db;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }}
            th, td {{
                border: 1px solid #ddd;
                padding: 12px;
                text-align: left;
            }}
            th {{
                background-color: #3498db;
                color: white;
            }}
            tr:nth-child(even) {{
                background-color: #f9f9f9;
            }}
            .footer {{
                margin-top: 30px;
                text-align: center;
                color: #7f8c8d;
                font-size: 12px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>📊 Data Quality Report</h1>
            <p>Generated: {timestamp}</p>
            <p>Upload ID: {upload_id}</p>
            
            <div class="summary">
                <div class="card">
                    <h3>Total Rows</h3>
                    <div class="number">{metrics.get('total_rows', 0)}</div>
                </div>
                <div class="card">
                    <h3>Total Columns</h3>
                    <div class="number">{len(metrics.get('column_metrics', {}))}</div>
                </div>
                <div class="card">
                    <h3>Duplicate Rows</h3>
                    <div class="number">{metrics.get('duplicate_count', 0)}</div>
                </div>
            </div>
            
            <h2>📋 Column Details</h2>
            <table>
                <thead>
                    <tr><th>Column Name</th><th>Data Type</th><th>Null Count</th><th>Null %</th><th>Unique Values</th></tr>
                </thead>
                <tbody>
    """
    
    for col, col_metrics in metrics.get('column_metrics', {}).items():
        html += f"""
                    <tr>
                        <td>{col}</td>
                        <td>{col_metrics.get('data_type', 'unknown')}</td>
                        <td>{col_metrics.get('null_count', 0)}</td>
                        <td>{col_metrics.get('null_percentage', 0)}%</td>
                        <td>{col_metrics.get('unique_count', 0)}</td>
                    </tr>
        """
    
    html += """
                </tbody>
            </table>
            
            <div class="footer">
                <p>Report generated by Data Management Platform (DMP)</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html

def save_html_report(upload_id, metrics, output_path):
    """Save HTML report to file"""
    
    html_content = generate_html_report(upload_id, metrics)
    
    with open(output_path, 'w') as f:
        f.write(html_content)
    
    return output_path